version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm test
  post_build:
    commands:
      - zip -r app.zip .
artifacts:
  files: app.zip

cache:
  paths:
    - node_modules/

